config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :my_friends
  get 'home/index'
  get 'home/about'
  get 'home/sign_out_user'
  root "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/my_friend.rb
class MyFriend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :my_friend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user! 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end

  def sign_out_user
    sign_out  current_user
    redirect_to new_user_session_path
  end
end

app/controllers/my_friends_controller.rb
class MyFriendsController < ApplicationController
  before_action :set_my_friend, only: %i[ show edit update destroy ]

  # GET /my_friends or /my_friends.json
  def index
    @my_friends = MyFriend.all
  end

  # GET /my_friends/1 or /my_friends/1.json
  def show
  end

  # GET /my_friends/new
  def new
    @my_friend = MyFriend.new
  end

  # GET /my_friends/1/edit
  def edit
  end

  # POST /my_friends or /my_friends.json
  def create
    @my_friend = MyFriend.new(my_friend_params)
    @my_friend.user_id = current_user.id
    respond_to do |format|
      if @my_friend.save
        format.html { redirect_to my_friend_url(@my_friend), notice: "My friend was successfully created." }
        format.json { render :show, status: :created, location: @my_friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_friends/1 or /my_friends/1.json
  def update
    respond_to do |format|
      if @my_friend.update(my_friend_params)
        format.html { redirect_to my_friend_url(@my_friend), notice: "My friend was successfully updated." }
        format.json { render :show, status: :ok, location: @my_friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_friends/1 or /my_friends/1.json
  def destroy
    @my_friend.destroy

    respond_to do |format|
      format.html { redirect_to my_friends_url, notice: "My friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_friend
      @my_friend = MyFriend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_friend_params
            params.require(:my_friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_friends_helper.rb
module MyFriendsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Freind App',root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us',home_about_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to 'My friends list', my_friends_path, class:"navbar-brand" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Add friends', new_my_friend_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', home_sign_out_user_path,  class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile',  edit_user_registration_path, class:"navbar-brand" %>
        </li>
        <% else %>

        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:"navbar-brand" %>
        </li>
          <% end %>      

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>
	Aishwary Goudar

</h1>

app/views/home/index.html.erb
<h1>Friendship is a relationship of mutual affection between people. It is a stronger form of interpersonal bond than an "acquaintance" or an "association", such as a classmate, neighbor, coworker, or colleague</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Friend</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container" >
      <br/>
    <%= yield %>
    
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/my_friends/_form.html.erb
<%= form_with(model: my_friend) do |form| %>
  <% if my_friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(my_friend.errors.count, "error") %> prohibited this my_friend from being saved:</h2>

      <ul>
        <% my_friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/my_friends/_my_friend.html.erb
<div id="<%= dom_id my_friend %>">
  <p>
    <strong>First name:</strong>
    <%= my_friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= my_friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= my_friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= my_friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= my_friend.twitter %>
  </p>

</div>

app/views/my_friends/edit.html.erb
<h1>Editing my friend</h1>

<%= render "form", my_friend: @my_friend %>

<br>

<div>
  <%= link_to "Show this my friend", @my_friend %> |
  <%= link_to "Back to my friends", my_friends_path %>
</div>

app/views/my_friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>My friends</h1>

<div id="my_friends">
  <% @my_friends.each do |my_friend| %>
    <%= render my_friend %>
    <p>
      <%= link_to "Show this my friend", my_friend %>
    </p>
  <% end %>
</div>

<%= link_to "New my friend", new_my_friend_path %>

app/views/my_friends/new.html.erb
<h1>New my friend</h1>

<%= render "form", my_friend: @my_friend %>

<br>

<div>
  <%= link_to "Back to my friends", my_friends_path %>
</div>

app/views/my_friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @my_friend %>

<div>

  <% if current_user.id == @my_friend.user_id %>
  <%= link_to "Edit this my friend", edit_my_friend_path(@my_friend) %> | <%end%>
  <%= link_to "Back to my friends", my_friends_path %>
  <% if current_user.id == @my_friend.user_id %>
    <%= button_to "Destroy this my friend", @my_friend, method: :delete %>
  <%end%>
</div>